# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python package

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v2.2.0
      # with:
      #   chromedriver-version: "118.0.5993.70"
    - run: |
        which chromedriver
        chromedriver -v


